#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicCarrental_Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ChicRentalDB")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBDataContext() : 
				base(global::ChicCarrental_Models.Properties.Settings.Default.ChicRentalDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_katon")]
		public ISingleResult<sp_katonResult> sp_katon()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_katonResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_katonResult
	{
		
		private int _price_id;
		
		private int _car_branch_id;
		
		private int _numdate;
		
		private System.Nullable<System.DateTime> _start_date;
		
		private System.Nullable<System.DateTime> _end_date;
		
		private System.Nullable<decimal> _price_cost;
		
		private System.Nullable<decimal> _price;
		
		private string _price_code;
		
		private System.Nullable<decimal> _paynow;
		
		private string _paynow_type;
		
		private System.Nullable<System.DateTime> _add_date;
		
		public sp_katonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_id", DbType="Int NOT NULL")]
		public int price_id
		{
			get
			{
				return this._price_id;
			}
			set
			{
				if ((this._price_id != value))
				{
					this._price_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_branch_id", DbType="Int NOT NULL")]
		public int car_branch_id
		{
			get
			{
				return this._car_branch_id;
			}
			set
			{
				if ((this._car_branch_id != value))
				{
					this._car_branch_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numdate", DbType="Int NOT NULL")]
		public int numdate
		{
			get
			{
				return this._numdate;
			}
			set
			{
				if ((this._numdate != value))
				{
					this._numdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> start_date
		{
			get
			{
				return this._start_date;
			}
			set
			{
				if ((this._start_date != value))
				{
					this._start_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> end_date
		{
			get
			{
				return this._end_date;
			}
			set
			{
				if ((this._end_date != value))
				{
					this._end_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_cost", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> price_cost
		{
			get
			{
				return this._price_cost;
			}
			set
			{
				if ((this._price_cost != value))
				{
					this._price_cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_code", DbType="NVarChar(50)")]
		public string price_code
		{
			get
			{
				return this._price_code;
			}
			set
			{
				if ((this._price_code != value))
				{
					this._price_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paynow", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> paynow
		{
			get
			{
				return this._paynow;
			}
			set
			{
				if ((this._paynow != value))
				{
					this._paynow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paynow_type", DbType="NVarChar(50)")]
		public string paynow_type
		{
			get
			{
				return this._paynow_type;
			}
			set
			{
				if ((this._paynow_type != value))
				{
					this._paynow_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> add_date
		{
			get
			{
				return this._add_date;
			}
			set
			{
				if ((this._add_date != value))
				{
					this._add_date = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
